substitutions:
  dev_name: kr-sonoff-001
  
esphome:
  name: ${dev_name}
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid_password
  manual_ip:
    static_ip: 192.168.1.33
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  #ap:
  #  ssid: !secret ap_ssid
  #  password: !secret ap_ssid_password
  domain: .localhome    

web_server:
  port: 80


api:
  password: !secret api_password 

ota:
  password: !secret ota_password
  
logger:

sensor:
  - platform: uptime
    name: ${dev_name}_uptime

  - platform: wifi_signal
    name: ${dev_name}_wifi_signal
    update_interval: 30s
    

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${dev_name}_button
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin: GPIO2
    name:   ${dev_name}_PIR Sensor
    device_class: motion
#----------------------------------    
switch:
  - platform: restart
    name: ${dev_name}_restart
    
  - platform: gpio
    name: ${dev_name}_relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: no

text_sensor:
  - platform: version
    name: ${dev_name}_version    
  - platform: wifi_info
    ip_address:
      name: ${dev_name}_IP
    ssid:
      name: ${dev_name}_SSID
    # bssid:
    #   name: ${dev_name}_BSSID
    mac_address:
      name: ${dev_name}_mac_wifi