substitutions:
  dev_name: sonoff-dual-r2-001

esphome:
  name: ${dev_name}
  platform: ESP8266
  board: esp01_1m
  # arduino_version: 2.4.2

wifi:
  ssid: "netis_05BC22"
  password: "password"
  #ssid: !secret wifi_ssid
  #password: !secret wifi_ssid_password
  manual_ip:
    static_ip: 192.168.1.31
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff Dual Hotspot"
    password: "rfvtgbyhn_01"

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  # password: "EspAdminn"
  encryption:
    key: EbGIXoGfaZNDj1/J3Vq83jAj6GOZI8wqzVSItovJjCY=

ota:
  password: "EspAdminn"

web_server:
  port: 80
  version: 1
  auth:
    username: admin
    password: password
  
#switch:
#  - platform: gpio
#    pin: GPIO5
#    name: "Relay 1"
#  - platform: gpio
#    pin: GPIO12
#    name: "Relay 2"


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: ${dev_name}_button
    on_press:
        - switch.turn_off: relay1
        - switch.turn_off: relay2
    #on_press:
    #  #- switch.toggle: relay
    #  - switch.turn_off: relay
    #  #- switch.toggle: relay2
    #  - switch.turn_off: relay2

#  - platform: status
#    name: "Switch Status"
    
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: True
    name: ${dev_name}_button0
    #toggle only relay1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO09
      mode: INPUT_PULLUP
      inverted: True
    name: ${dev_name}_button1
    #toggle only relay2
    on_press:
      - switch.toggle: relay2

switch:
  - platform: gpio
    name: ${dev_name}_relay2
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: ${dev_name}_relay1
    pin: GPIO05
    id: relay2
  #- platform: shutdown
  #  name: "${dev_name}_shutdown"
  - platform: restart
    name: ${dev_name}_restart

status_led:
  pin:
    number: GPIO13
    inverted: no

sensor:
  - platform: wifi_signal
    name: ${dev_name}_wifi_signal
    update_interval: 30s
  - platform: uptime
    name: ${dev_name}_uptime
    update_interval: 120s

  - platform: dht
    pin: GPIO3
    temperature:
      name: "${dev_name}_Room_Temperature"
    humidity:
      name: "${dev_name}_Room_Humidity"
    model: DHT11  
    update_interval: 30s  

  
text_sensor:
  - platform: version
    name: ${dev_name}_version    
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address